# Generated by Django 5.1.1 on 2024-09-24 11:46

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(choices=[('BASIC', 'Basic'), ('STANDARD', 'Standard'), ('PREMIUM', 'Premium')], max_length=10)),
                ('description', models.CharField(max_length=250)),
                ('cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SuperUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('image', models.ImageField(null=True, upload_to='uploads')),
                ('phone', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=11), size=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('superuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='login.superuser')),
                ('reviews', models.CharField(max_length=250)),
                ('years_of_experience', models.IntegerField()),
                ('avg_rating', models.FloatField()),
                ('salary', models.FloatField()),
                ('active_users', models.IntegerField()),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainers', to='login.plan')),
            ],
            options={
                'abstract': False,
            },
            bases=('login.superuser',),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('superuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='login.superuser')),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('subscribed_date', models.DateField()),
                ('end_date', models.DateField()),
                ('assigned_trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='login.trainer')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='login.plan')),
            ],
            options={
                'abstract': False,
            },
            bases=('login.superuser',),
        ),
    ]
