# Generated by Django 5.1.1 on 2024-09-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/plans'),
        ),
    ]
