# Generated by Django 5.1.1 on 2024-09-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_plan_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='image',
            field=models.ImageField(null=True, upload_to='plans'),
        ),
        migrations.AlterField(
            model_name='superuser',
            name='image',
            field=models.ImageField(null=True, upload_to='SuperUser'),
        ),
    ]
